- name: Create openvpn config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{openvpn_config_file}}.conf"
    owner: root
    group: root
  notify:
    - restart openvpn

- name: create openvpn client config directory
  file:
    path: "/etc/openvpn/ccd"
    state: directory

- name: create openvpn client specific config files
  template:
    src: ccd.j2
    dest: "/etc/openvpn/ccd/OpenVPN-Client-{{inventory_hostname}}-{{ item.key }}"
    owner: root
    group: root
  with_dict: "{{openvpn_private_subnets}}"
  when: openvpn_private_subnets is defined

- name: Install LDAP config
  template:
    src: ldap.conf.j2
    dest: "{{ openvpn_base_dir }}/auth/ldap.conf"
    owner: root
    group: root
  when: openvpn_use_ldap

- name: Copy openvpn logrotate config file
  copy:
    src: openvpn_logrotate.conf
    dest: /etc/logrotate.d/openvpn.conf
    owner: root
    group: root
    mode: 0400
  when: ansible_os_family != 'Solaris'

- name: Setup openvpn auto-start & start
  service:
    name: "{{openvpn_service_name}}"
    enabled: yes
    state: started
